"use strict";
const issuer="https://keycloak.ai-platform.local/realms/ai-platform";
const clientId="ai-platform-portal";
const redirectUri="https://api.ai-platform.local/portal/";
const $=id=>document.getElementById(id);
let auth=null,principal=null,selected=null,requests=[],catalog=[];
function notice(message,error=false){$("notice").textContent=message;$("notice").className=error?"error":""}
function randomString(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("")}
function base64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function login(){const verifier=randomString()+randomString(),state=randomString();sessionStorage.setItem("portal-oauth-state",state);sessionStorage.setItem("portal-pkce-verifier",verifier);const challenge=base64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier))));const url=new URL(issuer+"/protocol/openid-connect/auth");url.search=new URLSearchParams({client_id:clientId,response_type:"code",scope:"openid profile email",redirect_uri:redirectUri,state,code_challenge:challenge,code_challenge_method:"S256"});location.assign(url.toString())}
async function tokenRequest(params){const response=await fetch(issuer+"/protocol/openid-connect/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(params)});if(!response.ok)throw new Error("Identity token exchange failed");return response.json()}
async function finishLogin(){const query=new URLSearchParams(location.search);if(query.has("error"))throw new Error("Sign in was cancelled or denied");if(!query.has("code"))return;const state=sessionStorage.getItem("portal-oauth-state"),verifier=sessionStorage.getItem("portal-pkce-verifier");if(!state||!verifier||state!==query.get("state"))throw new Error("Invalid sign-in state");sessionStorage.removeItem("portal-oauth-state");sessionStorage.removeItem("portal-pkce-verifier");const tokens=await tokenRequest({grant_type:"authorization_code",client_id:clientId,code:query.get("code"),redirect_uri:redirectUri,code_verifier:verifier});auth={...tokens,expiresAt:Date.now()+tokens.expires_in*1000};history.replaceState({},"","/portal/");await initializeWorkspace()}
async function bearer(){if(!auth)throw new Error("Sign in required");if(auth.expiresAt<Date.now()+30000){if(!auth.refresh_token)throw new Error("Session expired; sign in again");const tokens=await tokenRequest({grant_type:"refresh_token",client_id:clientId,refresh_token:auth.refresh_token});auth={...tokens,expiresAt:Date.now()+tokens.expires_in*1000}}return auth.access_token}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...options.headers,Authorization:"Bearer "+await bearer(),...(options.body?{"Content-Type":"application/json"}:{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload.detail==="string"?payload.detail:"Request failed ("+response.status+")");return payload}
function element(tag,text,className){const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node}
function field(grid,title,value){const box=document.createElement("div");box.append(element("span",title),element("strong",String(value??"-")));grid.append(box)}
function updateEnvironments(){const model=catalog.find(item=>item.name===$("model-name").value);const select=$("environment"),current=select.value;select.replaceChildren();for(const value of model?.environments??[]){const option=element("option",value==="dev"?"Development":"Staging");option.value=value;select.append(option)}if([...select.options].some(option=>option.value===current))select.value=current}
async function loadCatalog(){catalog=await api("/catalog/models");const select=$("model-name");select.replaceChildren();for(const model of catalog){const option=element("option",model.display_name);option.value=model.name;option.title=model.description+" Owner: "+model.owner+" Minimum macro F1: "+model.minimum_macro_f1;select.append(option)}if(!catalog.length)throw new Error("No deployable models are registered");updateEnvironments()}
async function initializeWorkspace(){principal=await api("/me");$("signed-out").hidden=true;$("workspace").hidden=false;$("identity").textContent=principal.username+" | "+principal.tenant_id;$("auth-button").textContent="Sign out";$("stat-tenant").textContent=principal.tenant_id;$("request-panel").hidden=!principal.roles.some(role=>["data-scientist","ml-engineer","platform-admin"].includes(role));await loadCatalog();await loadRequests()}
async function loadRequests(){requests=await api("/deployments");$("stat-total").textContent=requests.length;$("stat-pending").textContent=requests.filter(r=>r.status==="pending_approval").length;$("stat-approved").textContent=requests.filter(r=>r.status==="approved").length;const list=$("requests");list.replaceChildren();if(!requests.length)list.append(element("p","No deployment requests yet.","muted"));for(const item of requests){const button=element("button","","request-item"+(item.request_id===selected?" selected":""));button.type="button";const line=element("div","","request-line");line.append(element("strong",item.model_name),element("span",item.status.replaceAll("_"," "),"badge "+item.status));button.append(line,element("small",item.environment+" | version "+item.model_version+" | "+item.requested_by));button.addEventListener("click",()=>selectRequest(item.request_id));list.append(button)}if(selected&&requests.some(r=>r.request_id===selected))await selectRequest(selected)}
async function selectRequest(id){selected=id;const [item,audit]=await Promise.all([api("/deployments/"+encodeURIComponent(id)),api("/deployments/"+encodeURIComponent(id)+"/audit")]);$("selected-id").textContent=id;const detail=$("details");detail.replaceChildren();const grid=element("div","","detail-grid");field(grid,"Model",item.model_name);field(grid,"Version",item.model_version);field(grid,"Environment",item.environment);field(grid,"Policy decision",item.status.replaceAll("_"," "));field(grid,"Execution",item.execution_status);field(grid,"Result",item.execution_message);field(grid,"Requested by",item.requested_by);field(grid,"Argo sync",item.orchestration?.result?.argocd?.sync_status);field(grid,"Argo health",item.orchestration?.result?.argocd?.health_status);field(grid,"Crossplane",item.orchestration?.result?.crossplane?.ready===true?"Ready":item.orchestration?.result?.gitops?.workspace?"Reconciling":"Not required");field(grid,"Workspace PVC",item.orchestration?.result?.crossplane?.pvc_name);detail.append(grid);const argoUrl=item.orchestration?.result?.argocd?.application_url;if(argoUrl){const link=element("a","Open Argo application");link.href=argoUrl;link.target="_blank";link.rel="noopener";detail.append(link)}$("approval-actions").hidden=!(item.status==="pending_approval"&&principal.roles.includes("approver")&&item.requested_by!==principal.username);const trail=$("audit");trail.replaceChildren();for(const event of audit){const row=element("div","","audit-item");row.append(element("span",event.event_type.replaceAll("."," / ")+" - "+event.actor),element("small",new Date(event.created_at).toLocaleString()));trail.append(row)}if(!audit.length)trail.append(element("p","No audit events.","muted"))}
async function createRequest(event){event.preventDefault();try{const item=await api("/deployments",{method:"POST",body:JSON.stringify({tenant_id:principal.tenant_id,model_name:$("model-name").value,model_version:$("model-version").value,environment:$("environment").value})});await api("/deployments/"+item.request_id+"/submit",{method:"POST"});notice("Request submitted for approval.");await loadRequests();await selectRequest(item.request_id)}catch(error){notice(error.message,true)}}
async function decide(decision){if(!selected)return;try{const reason=$("decision-reason").value.trim();if(reason.length<3)throw new Error("Enter a reason of at least three characters");await api("/deployments/"+selected+"/decision",{method:"POST",body:JSON.stringify({decision,reason})});notice("Request "+decision+".");await loadRequests()}catch(error){notice(error.message,true)}}
function signOut(){const idToken=auth?.id_token;auth=null;principal=null;selected=null;requests=[];sessionStorage.removeItem("portal-oauth-state");sessionStorage.removeItem("portal-pkce-verifier");$("workspace").hidden=true;$("signed-out").hidden=false;$("identity").textContent="Signed out";$("auth-button").textContent="Sign in";const url=new URL(issuer+"/protocol/openid-connect/logout");url.search=new URLSearchParams({client_id:clientId,post_logout_redirect_uri:redirectUri,...(idToken?{id_token_hint:idToken}:{})});location.assign(url.toString())}
$("auth-button").addEventListener("click",()=>auth?signOut():login());$("welcome-login").addEventListener("click",login);$("deployment-form").addEventListener("submit",createRequest);$("model-name").addEventListener("change",updateEnvironments);$("refresh").addEventListener("click",()=>loadRequests().catch(e=>notice(e.message,true)));$("approve").addEventListener("click",()=>decide("approved"));$("reject").addEventListener("click",()=>decide("rejected"));finishLogin().catch(error=>{history.replaceState({},"","/portal/");notice(error.message,true)});setInterval(()=>{if(auth)loadRequests().catch(e=>notice(e.message,true))},15000);
