apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ai-platform-dev

nameSuffix: -dev

replicas:
  - name: platform-smoke-test
    count: 1

labels:
  - pairs:
      platform.example.com/environment: dev

images:
  - name: nginx
    newName: nginx
    newTag: 1.31.5-alpine3.24
