apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform-security
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  description: Enterprise identity and security services

  sourceRepos:
    - https://github.com/nolet7/ai-platform-lab.git

  destinations:
    - namespace: security
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: apps
      kind: StatefulSet

    - group: ""
      kind: Service

    - group: ""
      kind: ConfigMap

  orphanedResources:
    warn: true
