apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform-crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  description: Crossplane local control plane
  sourceRepos:
    - https://charts.crossplane.io/stable
  destinations:
    - namespace: crossplane-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment