apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  description: Restricted project for AI Platform application workloads

  sourceRepos:
    - https://github.com/nolet7/ai-platform-lab.git

  destinations:
    - namespace: ai-platform
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: apps
      kind: StatefulSet

    - group: ""
      kind: Service

    - group: ""
      kind: ConfigMap

    - group: ""
      kind: Secret

  orphanedResources:
    warn: true
