apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: c1587cadf825c047f0db97c8f58b67695689e26c
    path: gitops/platform/backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
