apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-environments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/platform/namespaces

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
