apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-smoke-test-dev
  namespace: argocd

spec:
  project: ai-platform-dev

  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/workloads/platform-smoke-test-v2/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
