apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-edge
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: ai-platform-edge

  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/platform-edge

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
