apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-smoke-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: ai-platform-workloads

  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/workloads/platform-smoke-test

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
