apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crossplane-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: ai-platform-crossplane
  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/platform-infrastructure/crossplane/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Prune=false
      - SkipDryRunOnMissingResource=true