apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: ai-platform-observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 90.0.0
      helm:
        releaseName: kube-prometheus-stack
        skipCrds: true
        valueFiles:
          - $values/observability/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/nolet7/ai-platform-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - Prune=false