apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-smoke-test-staging
  namespace: argocd

spec:
  project: ai-platform-staging

  source:
    repoURL: https://github.com/nolet7/ai-platform-lab.git
    targetRevision: main
    path: gitops/workloads/platform-smoke-test-v2/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
