grafana:
  enabled: true

  env:
    GF_SERVER_DOMAIN: grafana.ai-platform.local
    GF_SERVER_ROOT_URL: https://grafana.ai-platform.local/
    GF_SERVER_PROTOCOL: http

  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

    datasources:
      enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi


prometheus:
  enabled: true

  prometheusSpec:
    externalUrl: https://prometheus.ai-platform.local
    retention: 2d

    resources:
      requests:
        cpu: 200m
        memory: 512Mi

      limits:
        cpu: "1"
        memory: 2Gi


alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

      limits:
        cpu: 250m
        memory: 256Mi


kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false
