[k8s_control]
k8s-control-01 ansible_host=10.10.10.10

[k8s_workers]
k8s-worker-01 ansible_host=10.10.10.11
k8s-worker-02 ansible_host=10.10.10.12

[k8s_cluster:children]
k8s_control
k8s_workers

[k8s_cluster:vars]
ansible_user=lateef
ansible_ssh_private_key_file=/home/lateef/.ssh/ai-platform-lab
