apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-platform-api-config
  namespace: ai-platform

data:
  OTEL_ENABLED: "true"

  OTEL_SERVICE_NAME:
    "ai-platform-api"

  OTEL_EXPORTER_OTLP_ENDPOINT:
    "otel-collector.observability.svc.cluster.local:4317"

  OTEL_EXPORTER_OTLP_INSECURE:
    "true"

  OTEL_TRACE_SAMPLE_RATIO:
    "1.0"
