apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
