apiVersion: v1
kind: Service

metadata:
  name: mlflow-postgres
  labels:
    app.kubernetes.io/name: mlflow-postgres
    app.kubernetes.io/component: metadata-store

spec:
  selector:
    app.kubernetes.io/name: mlflow-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

  type: ClusterIP
