apiVersion: v1
kind: Service

metadata:
  name: mlflow

  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: tracking-server

spec:
  selector:
    app.kubernetes.io/name: mlflow

  ports:
    - name: http
      port: 5000
      targetPort: http

  type: ClusterIP
