apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: observability

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-phase2p

rules:
  - apiGroups:
      - ""

    resources:
      - pods
      - pods/log
      - namespaces
      - nodes

    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-phase2p

roleRef:
  apiGroup:
    rbac.authorization.k8s.io

  kind:
    ClusterRole

  name:
    alloy-phase2p

subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: observability
