apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - loki-configmap.yaml
  - loki.yaml

  - tempo-configmap.yaml
  - tempo.yaml

  - otel-collector-configmap.yaml
  - otel-collector.yaml

  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy.yaml

  - grafana-datasources.yaml
