apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-api-config
data:
  OIDC_ISSUER: "http://localhost:8081/realms/ai-platform"
  OIDC_AUDIENCE: "ai-platform-api"
  OIDC_JWKS_URL: "http://keycloak.security.svc.cluster.local:8080/realms/ai-platform/protocol/openid-connect/certs"
