apiVersion: apps/v1
kind: Deployment

metadata:
  name: platform-api

spec:
  replicas: 2
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: platform-api

  template:
    metadata:
      annotations:
        platform.ai/config-revision: oidc-clean-issuer-2026-09-17
      labels:
        app: platform-api

    spec:
      serviceAccountName: platform-api
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true

        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: platform-api
          image: ai-platform-api:0.4.1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: platform-api-config

            - secretRef:
                name: platform-db-secret

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true

            capabilities:
              drop:
                - ALL

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http

            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health/live
              port: http

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
