apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: platform-api-migration

spec:
  podSelector:
    matchLabels:
      app: platform-api-migration

  policyTypes:
    - Egress

  egress:
    # PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app: platform-postgres

      ports:
        - protocol: TCP
          port: 5432

    # Kubernetes DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system

          podSelector:
            matchLabels:
              k8s-app: kube-dns

      ports:
        - protocol: UDP
          port: 53

        - protocol: TCP
          port: 53
