apiVersion: batch/v1
kind: Job

metadata:
  name: platform-api-db-migrate

  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180

  template:
    metadata:
      labels:
        app: platform-api-migration

    spec:
      restartPolicy: Never
      serviceAccountName: platform-api
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true

        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: migrate
          image: ai-platform-api:0.3.0
          imagePullPolicy: IfNotPresent

          command:
            - alembic
            - -c
            - /app/alembic.ini
            - upgrade
            - head

          envFrom:
            - secretRef:
                name: platform-db-secret

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true

            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 250m
              memory: 256Mi

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
