apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: platform-postgres

  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  podSelector:
    matchLabels:
      app: platform-postgres

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - platform-api
                  - platform-api-migration

      ports:
        - protocol: TCP
          port: 5432
