apiVersion: v1
kind: Service
metadata:
  name: platform-postgres

spec:
  clusterIP: None

  selector:
    app: platform-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
