apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-workspace-aggregate-to-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete