apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ai-platform-staging

nameSuffix: -staging

replicas:
  - name: platform-smoke-test
    count: 2

labels:
  - pairs:
      platform.example.com/environment: staging

images:
  - name: nginx
    newName: nginx
    newTag: 1.31.5-alpine3.24
