apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-platform-api
  namespace: ai-platform

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ai-platform-api

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8001

  egress:

    # Kubernetes DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Keycloak
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: security
      ports:
        - protocol: TCP
          port: 8080
