apiVersion: v1
kind: Service
metadata:
  name: ai-platform-api
  namespace: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform-api
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: ai-platform-api

  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: http
