apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ai-platform-prod

nameSuffix: -prod

replicas:
  - name: platform-smoke-test
    count: 3

labels:
  - pairs:
      platform.example.com/environment: prod
