apiVersion: v1
kind: ConfigMap

metadata:
  name: deployment-orchestrator-config

data:
  REDIS_HOST: platform-redis
  REDIS_PORT: "6379"

  QUEUE_NAME: deployments

  DISPATCH_INTERVAL_SECONDS: "5"
  DISPATCH_LEASE_SECONDS: "60"
  RETRY_DELAY_SECONDS: "15"
