apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-smoke-test
  labels:
    app: platform-smoke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-smoke-test
  template:
    metadata:
      labels:
        app: platform-smoke-test
    spec:
      containers:
        - name: web
          image: nginx:1.30.4-alpine3.24
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
