apiVersion: v1
kind: Service
metadata:
  name: tax-classifier

spec:
  selector:
    app.kubernetes.io/name: tax-classifier

  ports:
    - name: http
      port: 80
      targetPort: http

  type: ClusterIP
