apiVersion: v1
kind: ServiceAccount
metadata:
  name: tax-classifier-serving
  labels:
    app.kubernetes.io/name: tax-document-classifier
    app.kubernetes.io/component: serving
automountServiceAccountToken: false
secrets:
  - name: tax-classifier-s3
