apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: tax-document-classifier-tax-ml-team-dev
  labels:
    app.kubernetes.io/name: tax-document-classifier
    app.kubernetes.io/component: serving
    ai-platform.io/tenant: tax-ml-team
    ai-platform.io/environment: dev
    ai-platform.io/model-version: "1"
    ai-platform.io/model-id: m-021e2255280449de897f0b2981283d79
    ai-platform.io/dataset-version: synthetic-demo-v1
  annotations:
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/secretName: tax-classifier-s3
    ai-platform.io/request-id: "8ccb1a9d-d3e1-4e18-b2a5-051688525f46"
    ai-platform.io/run-id: "c7f6f3a7fb36426385ca9e0ec6949eb3"
    ai-platform.io/source-git-sha: "3a656eb486ea94c6e95ae7333d4358bf231299f0"
spec:
  predictor:
    serviceAccountName: tax-classifier-serving
    model:
      modelFormat:
        name: mlflow
      runtime: kserve-mlserver
      protocolVersion: v2
      storageUri: s3://mlflow-artifacts/2/models/m-021e2255280449de897f0b2981283d79/artifacts
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
